import java.util.Random;
import java.util.Scanner;

public class Lotto {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		int usernum1, usernum2, usernum3, usernum4, usernum5, usernum6;
		int compnum1, compnum2, compnum3, compnum4, compnum5, compnum6;
		int bonus;
		int counter1=0, counter2=0, counter3=0, counter4=0, counter5=0, counter6=0, losscounter=0;
		int useroption;
		int time;

		Scanner in=new Scanner(System.in);
		Random rnd=new Random();

		System.out.println("Would you like to");
		System.out.println("1 choose your own numbers or");
		System.out.println("2 have them randomly generated for you?");
		System.out.println("Please choose 1 or 2");
		useroption=in.nextInt();
		if (useroption==1){
			do{
				System.out.println("Please choose 6 numbers between 1 and 49 and hit enter afer each one.");

				usernum1=in.nextInt();
				usernum2=in.nextInt();
				usernum3=in.nextInt();
				usernum4=in.nextInt();
				usernum5=in.nextInt();
				usernum6=in.nextInt();

			}while (usernum1==usernum2||usernum1==usernum3||usernum1==usernum4||usernum1==usernum5||usernum1==usernum6||usernum2==usernum3||usernum2==usernum4||usernum2==usernum5||usernum2==usernum6&&usernum3==usernum4||usernum3==usernum5||usernum3==usernum6&&usernum4==usernum5||usernum4==usernum6&&usernum5==usernum6);

		}	else{
			do {
				System.out.println("We will randomly generate numbers for you");
				usernum1=rnd.nextInt (49-1+1)+1;
				usernum2=rnd.nextInt (49-1+1)+1;
				usernum3=rnd.nextInt (49-1+1)+1;
				usernum4=rnd.nextInt (49-1+1)+1;
				usernum5=rnd.nextInt (49-1+1)+1;
				usernum6=rnd.nextInt (49-1+1)+1;
			}  while (usernum1==usernum2||usernum1==usernum3||usernum1==usernum4||usernum1==usernum5||usernum1==usernum6&&usernum2==usernum3||usernum2==usernum4||usernum2==usernum5||usernum2==usernum6&&usernum3==usernum4||usernum3==usernum5||usernum3==usernum6&&usernum4==usernum5||usernum4==usernum6&&usernum5==usernum6);
			
		}do{
			do{
				compnum1=rnd.nextInt (49-1+1)+1;
				compnum2=rnd.nextInt (49-1+1)+1;
				compnum3=rnd.nextInt (49-1+1)+1;
				compnum4=rnd.nextInt (49-1+1)+1;
				compnum5=rnd.nextInt (49-1+1)+1;
				compnum6=rnd.nextInt (49-1+1)+1;
				bonus=rnd.nextInt(49-1+1)+1;
			}while (compnum1==compnum2||compnum1==compnum3||compnum1==compnum4||compnum1==compnum5||compnum1==compnum6&&compnum2==compnum3||compnum2==compnum4||compnum2==compnum5||compnum2==compnum6&&compnum3==compnum4||compnum3==compnum5||compnum3==compnum6&&compnum4==compnum5||compnum4==compnum6&&compnum5==compnum6&&bonus==compnum1||bonus==compnum2||bonus==compnum3||bonus==compnum4||bonus==compnum5||bonus==compnum6);
			
			if ((usernum1==compnum1||usernum1==compnum2||usernum1==compnum3||usernum1==compnum4||usernum1==compnum5||usernum1==compnum6||usernum2==compnum1||usernum2==compnum2||usernum2==compnum3||usernum2==compnum4||usernum2==compnum5||usernum2==compnum6||usernum3==compnum1||usernum3==compnum2||usernum3==compnum3||usernum3==compnum4||usernum3==compnum5||usernum3==compnum6||usernum4==compnum1||usernum4==compnum2||usernum4==compnum3||usernum4==compnum4||usernum4==compnum5||usernum4==compnum6||usernum5==compnum1||usernum5==compnum2||usernum5==compnum3||usernum5==compnum4||usernum5==compnum5||usernum5==compnum6||usernum6==compnum1||usernum6==compnum2||usernum6==compnum3||usernum6==compnum4||usernum6==compnum5||usernum6==compnum6)&&(usernum2==compnum1||usernum2==compnum2||usernum2==compnum3||usernum2==compnum4||usernum2==compnum5||usernum2==compnum6||usernum3==compnum1||usernum3==compnum2||usernum3==compnum3||usernum3==compnum4||usernum3==compnum5||usernum3==compnum6||usernum4==compnum1||usernum4==compnum2||usernum4==compnum3||usernum4==compnum4||usernum4==compnum5||usernum4==compnum6||usernum5==compnum1||usernum5==compnum2||usernum5==compnum3||usernum5==compnum4||usernum5==compnum5||usernum5==compnum6||usernum6==compnum1||usernum6==compnum2||usernum6==compnum3||usernum6==compnum4||usernum6==compnum5||usernum6==compnum6)){
				counter1++;
			}if ((usernum1==compnum1||usernum1==compnum2||usernum1==compnum3||usernum1==compnum4||usernum1==compnum5||usernum1==compnum6||usernum2==compnum1||usernum2==compnum2||usernum2==compnum3||usernum2==compnum4||usernum2==compnum5||usernum2==compnum6||usernum3==compnum1||usernum3==compnum2||usernum3==compnum3||usernum3==compnum4||usernum3==compnum5||usernum3==compnum6||usernum4==compnum1||usernum4==compnum2||usernum4==compnum3||usernum4==compnum4||usernum4==compnum5||usernum4==compnum6||usernum5==compnum1||usernum5==compnum2||usernum5==compnum3||usernum5==compnum4||usernum5==compnum5||usernum5==compnum6||usernum6==compnum1||usernum6==compnum2||usernum6==compnum3||usernum6==compnum4||usernum6==compnum5||usernum6==compnum6)&&(usernum2==compnum1||usernum2==compnum2||usernum2==compnum3||usernum2==compnum4||usernum2==compnum5||usernum2==compnum6||usernum3==compnum1||usernum3==compnum2||usernum3==compnum3||usernum3==compnum4||usernum3==compnum5||usernum3==compnum6||usernum4==compnum1||usernum4==compnum2||usernum4==compnum3||usernum4==compnum4||usernum4==compnum5||usernum4==compnum6||usernum5==compnum1||usernum5==compnum2||usernum5==compnum3||usernum5==compnum4||usernum5==compnum5||usernum5==compnum6||usernum6==compnum1||usernum6==compnum2||usernum6==compnum3||usernum6==compnum4||usernum6==compnum5||usernum6==compnum6)&&(usernum1==bonus||usernum2==bonus||usernum3==bonus||usernum4==bonus||usernum5==bonus||usernum6==bonus)){
				counter2++;
			}if ((usernum1==compnum1||usernum1==compnum2||usernum1==compnum3||usernum1==compnum4||usernum1==compnum5||usernum1==compnum6||usernum2==compnum1||usernum2==compnum2||usernum2==compnum3||usernum2==compnum4||usernum2==compnum5||usernum2==compnum6||usernum3==compnum1||usernum3==compnum2||usernum3==compnum3||usernum3==compnum4||usernum3==compnum5||usernum3==compnum6||usernum4==compnum1||usernum4==compnum2||usernum4==compnum3||usernum4==compnum4||usernum4==compnum5||usernum4==compnum6||usernum5==compnum1||usernum5==compnum2||usernum5==compnum3||usernum5==compnum4||usernum5==compnum5||usernum5==compnum6||usernum6==compnum1||usernum6==compnum2||usernum6==compnum3||usernum6==compnum4||usernum6==compnum5||usernum6==compnum6)&&(usernum2==compnum1||usernum2==compnum2||usernum2==compnum3||usernum2==compnum4||usernum2==compnum5||usernum2==compnum6||usernum3==compnum1||usernum3==compnum2||usernum3==compnum3||usernum3==compnum4||usernum3==compnum5||usernum3==compnum6||usernum4==compnum1||usernum4==compnum2||usernum4==compnum3||usernum4==compnum4||usernum4==compnum5||usernum4==compnum6||usernum5==compnum1||usernum5==compnum2||usernum5==compnum3||usernum5==compnum4||usernum5==compnum5||usernum5==compnum6||usernum6==compnum1||usernum6==compnum2||usernum6==compnum3||usernum6==compnum4||usernum6==compnum5||usernum6==compnum6)&&(usernum3==compnum1||usernum3==compnum2||usernum3==compnum3||usernum3==compnum4||usernum3==compnum5||usernum3==compnum6||usernum4==compnum1||usernum4==compnum2||usernum4==compnum3||usernum4==compnum4||usernum4==compnum5||usernum4==compnum6||usernum5==compnum1||usernum5==compnum2||usernum5==compnum3||usernum5==compnum4||usernum5==compnum5||usernum5==compnum6||usernum6==compnum1||usernum6==compnum2||usernum6==compnum3||usernum6==compnum4||usernum6==compnum5||usernum6==compnum6)){
				counter3++;
			}if ((usernum1==compnum1||usernum1==compnum2||usernum1==compnum3||usernum1==compnum4||usernum1==compnum5||usernum1==compnum6||usernum2==compnum1||usernum2==compnum2||usernum2==compnum3||usernum2==compnum4||usernum2==compnum5||usernum2==compnum6||usernum3==compnum1||usernum3==compnum2||usernum3==compnum3||usernum3==compnum4||usernum3==compnum5||usernum3==compnum6||usernum4==compnum1||usernum4==compnum2||usernum4==compnum3||usernum4==compnum4||usernum4==compnum5||usernum4==compnum6||usernum5==compnum1||usernum5==compnum2||usernum5==compnum3||usernum5==compnum4||usernum5==compnum5||usernum5==compnum6||usernum6==compnum1||usernum6==compnum2||usernum6==compnum3||usernum6==compnum4||usernum6==compnum5||usernum6==compnum6)&&(usernum2==compnum1||usernum2==compnum2||usernum2==compnum3||usernum2==compnum4||usernum2==compnum5||usernum2==compnum6||usernum3==compnum1||usernum3==compnum2||usernum3==compnum3||usernum3==compnum4||usernum3==compnum5||usernum3==compnum6||usernum4==compnum1||usernum4==compnum2||usernum4==compnum3||usernum4==compnum4||usernum4==compnum5||usernum4==compnum6||usernum5==compnum1||usernum5==compnum2||usernum5==compnum3||usernum5==compnum4||usernum5==compnum5||usernum5==compnum6||usernum6==compnum1||usernum6==compnum2||usernum6==compnum3||usernum6==compnum4||usernum6==compnum5||usernum6==compnum6)&&(usernum3==compnum1||usernum3==compnum2||usernum3==compnum3||usernum3==compnum4||usernum3==compnum5||usernum3==compnum6||usernum4==compnum1||usernum4==compnum2||usernum4==compnum3||usernum4==compnum4||usernum4==compnum5||usernum4==compnum6||usernum5==compnum1||usernum5==compnum2||usernum5==compnum3||usernum5==compnum4||usernum5==compnum5||usernum5==compnum6||usernum6==compnum1||usernum6==compnum2||usernum6==compnum3||usernum6==compnum4||usernum6==compnum5||usernum6==compnum6)&&(usernum4==compnum2||usernum4==compnum3||usernum4==compnum4||usernum4==compnum5||usernum4==compnum6||usernum5==compnum1||usernum5==compnum2||usernum5==compnum3||usernum5==compnum4||usernum5==compnum5||usernum5==compnum6||usernum6==compnum1||usernum6==compnum2||usernum6==compnum3||usernum6==compnum4||usernum6==compnum5||usernum6==compnum6)){
				counter4++; 
			}if ((usernum1==compnum1||usernum1==compnum2||usernum1==compnum3||usernum1==compnum4||usernum1==compnum5||usernum1==compnum6||usernum2==compnum1||usernum2==compnum2||usernum2==compnum3||usernum2==compnum4||usernum2==compnum5||usernum2==compnum6||usernum3==compnum1||usernum3==compnum2||usernum3==compnum3||usernum3==compnum4||usernum3==compnum5||usernum3==compnum6||usernum4==compnum1||usernum4==compnum2||usernum4==compnum3||usernum4==compnum4||usernum4==compnum5||usernum4==compnum6||usernum5==compnum1||usernum5==compnum2||usernum5==compnum3||usernum5==compnum4||usernum5==compnum5||usernum5==compnum6||usernum6==compnum1||usernum6==compnum2||usernum6==compnum3||usernum6==compnum4||usernum6==compnum5||usernum6==compnum6)&&(usernum2==compnum1||usernum2==compnum2||usernum2==compnum3||usernum2==compnum4||usernum2==compnum5||usernum2==compnum6||usernum3==compnum1||usernum3==compnum2||usernum3==compnum3||usernum3==compnum4||usernum3==compnum5||usernum3==compnum6||usernum4==compnum1||usernum4==compnum2||usernum4==compnum3||usernum4==compnum4||usernum4==compnum5||usernum4==compnum6||usernum5==compnum1||usernum5==compnum2||usernum5==compnum3||usernum5==compnum4||usernum5==compnum5||usernum5==compnum6||usernum6==compnum1||usernum6==compnum2||usernum6==compnum3||usernum6==compnum4||usernum6==compnum5||usernum6==compnum6)&&(usernum3==compnum1||usernum3==compnum2||usernum3==compnum3||usernum3==compnum4||usernum3==compnum5||usernum3==compnum6||usernum4==compnum1||usernum4==compnum2||usernum4==compnum3||usernum4==compnum4||usernum4==compnum5||usernum4==compnum6||usernum5==compnum1||usernum5==compnum2||usernum5==compnum3||usernum5==compnum4||usernum5==compnum5||usernum5==compnum6||usernum6==compnum1||usernum6==compnum2||usernum6==compnum3||usernum6==compnum4||usernum6==compnum5||usernum6==compnum6)&&(usernum4==compnum2||usernum4==compnum3||usernum4==compnum4||usernum4==compnum5||usernum4==compnum6||usernum5==compnum1||usernum5==compnum2||usernum5==compnum3||usernum5==compnum4||usernum5==compnum5||usernum5==compnum6||usernum6==compnum1||usernum6==compnum2||usernum6==compnum3||usernum6==compnum4||usernum6==compnum5||usernum6==compnum6)&&(usernum5==compnum1||usernum5==compnum2||usernum5==compnum3||usernum5==compnum4||usernum5==compnum5||usernum5==compnum6||usernum6==compnum1||usernum6==compnum2||usernum6==compnum3||usernum6==compnum4||usernum6==compnum5||usernum6==compnum6)&&(usernum1==bonus||usernum2==bonus||usernum3==bonus||usernum4==bonus||usernum5==bonus||usernum6==bonus)){
				counter5++;
			}if ((usernum1==compnum1||usernum1==compnum2||usernum1==compnum3||usernum1==compnum4||usernum1==compnum5||usernum1==compnum6||usernum2==compnum1||usernum2==compnum2||usernum2==compnum3||usernum2==compnum4||usernum2==compnum5||usernum2==compnum6||usernum3==compnum1||usernum3==compnum2||usernum3==compnum3||usernum3==compnum4||usernum3==compnum5||usernum3==compnum6||usernum4==compnum1||usernum4==compnum2||usernum4==compnum3||usernum4==compnum4||usernum4==compnum5||usernum4==compnum6||usernum5==compnum1||usernum5==compnum2||usernum5==compnum3||usernum5==compnum4||usernum5==compnum5||usernum5==compnum6||usernum6==compnum1||usernum6==compnum2||usernum6==compnum3||usernum6==compnum4||usernum6==compnum5||usernum6==compnum6)&&(usernum2==compnum1||usernum2==compnum2||usernum2==compnum3||usernum2==compnum4||usernum2==compnum5||usernum2==compnum6||usernum3==compnum1||usernum3==compnum2||usernum3==compnum3||usernum3==compnum4||usernum3==compnum5||usernum3==compnum6||usernum4==compnum1||usernum4==compnum2||usernum4==compnum3||usernum4==compnum4||usernum4==compnum5||usernum4==compnum6||usernum5==compnum1||usernum5==compnum2||usernum5==compnum3||usernum5==compnum4||usernum5==compnum5||usernum5==compnum6||usernum6==compnum1||usernum6==compnum2||usernum6==compnum3||usernum6==compnum4||usernum6==compnum5||usernum6==compnum6)&&(usernum3==compnum1||usernum3==compnum2||usernum3==compnum3||usernum3==compnum4||usernum3==compnum5||usernum3==compnum6||usernum4==compnum1||usernum4==compnum2||usernum4==compnum3||usernum4==compnum4||usernum4==compnum5||usernum4==compnum6||usernum5==compnum1||usernum5==compnum2||usernum5==compnum3||usernum5==compnum4||usernum5==compnum5||usernum5==compnum6||usernum6==compnum1||usernum6==compnum2||usernum6==compnum3||usernum6==compnum4||usernum6==compnum5||usernum6==compnum6)&&(usernum4==compnum2||usernum4==compnum3||usernum4==compnum4||usernum4==compnum5||usernum4==compnum6||usernum5==compnum1||usernum5==compnum2||usernum5==compnum3||usernum5==compnum4||usernum5==compnum5||usernum5==compnum6||usernum6==compnum1||usernum6==compnum2||usernum6==compnum3||usernum6==compnum4||usernum6==compnum5||usernum6==compnum6)&&(usernum5==compnum1||usernum5==compnum2||usernum5==compnum3||usernum5==compnum4||usernum5==compnum5||usernum5==compnum6||usernum6==compnum1||usernum6==compnum2||usernum6==compnum3||usernum6==compnum4||usernum6==compnum5||usernum6==compnum6)){
				counter6++;
			}else if ((usernum1!=compnum1||usernum1!=compnum2||usernum1!=compnum3||usernum1!=compnum4||usernum1!=compnum5||usernum1!=compnum6||usernum2!=compnum1||usernum2!=compnum2||usernum2!=compnum3||usernum2!=compnum4||usernum2!=compnum5||usernum2!=compnum6||usernum3!=compnum1||usernum3!=compnum2||usernum3!=compnum3||usernum3!=compnum4||usernum3!=compnum5||usernum3!=compnum6||usernum4!=compnum1||usernum4!=compnum2||usernum4!=compnum3||usernum4!=compnum4||usernum4!=compnum5||usernum4!=compnum6||usernum5!=compnum1||usernum5!=compnum2||usernum5!=compnum3||usernum5!=compnum4||usernum5!=compnum5||usernum5!=compnum6||usernum6!=compnum1||usernum6!=compnum2||usernum6!=compnum3||usernum6!=compnum4||usernum6!=compnum5||usernum6!=compnum6)&&(usernum2!=compnum1||usernum2!=compnum2||usernum2!=compnum3||usernum2!=compnum4||usernum2!=compnum5||usernum2!=compnum6||usernum3!=compnum1||usernum3!=compnum2||usernum3!=compnum3||usernum3!=compnum4||usernum3!=compnum5||usernum3!=compnum6||usernum4!=compnum1||usernum4!=compnum2||usernum4!=compnum3||usernum4!=compnum4||usernum4!=compnum5||usernum4!=compnum6||usernum5!=compnum1||usernum5!=compnum2||usernum5!=compnum3||usernum5!=compnum4||usernum5!=compnum5||usernum5!=compnum6||usernum6!=compnum1||usernum6!=compnum2||usernum6!=compnum3||usernum6!=compnum4||usernum6!=compnum5||usernum6!=compnum6)&&(usernum3!=compnum1||usernum3!=compnum2||usernum3!=compnum3||usernum3!=compnum4||usernum3!=compnum5||usernum3!=compnum6||usernum4!=compnum1||usernum4!=compnum2||usernum4!=compnum3||usernum4!=compnum4||usernum4!=compnum5||usernum4!=compnum6||usernum5!=compnum1||usernum5!=compnum2||usernum5!=compnum3||usernum5!=compnum4||usernum5!=compnum5||usernum5!=compnum6||usernum6!=compnum1||usernum6!=compnum2||usernum6!=compnum3||usernum6!=compnum4||usernum6!=compnum5||usernum6!=compnum6)&&(usernum4!=compnum2||usernum4!=compnum3||usernum4!=compnum4||usernum4!=compnum5||usernum4!=compnum6||usernum5!=compnum1||usernum5!=compnum2||usernum5!=compnum3||usernum5!=compnum4||usernum5!=compnum5||usernum5!=compnum6||usernum6!=compnum1||usernum6!=compnum2||usernum6!=compnum3||usernum6!=compnum4||usernum6!=compnum5||usernum6!=compnum6)&&(usernum5!=compnum1||usernum5!=compnum2||usernum5!=compnum3||usernum5!=compnum4||usernum5!=compnum5||usernum5!=compnum6||usernum6!=compnum1||usernum6!=compnum2||usernum6!=compnum3||usernum6!=compnum4||usernum6!=compnum5||usernum6!=compnum6)&&(usernum6!=compnum1||usernum6!=compnum2||usernum6!=compnum3||usernum6!=compnum4||usernum6!=compnum5||usernum6!=compnum6)&&(usernum1!=bonus||usernum2!=bonus||usernum3!=bonus||usernum4!=bonus||usernum5!=bonus||usernum6!=bonus));
			losscounter++;
		} while((usernum1!=compnum1&&usernum1!=compnum2&&usernum1!=compnum3&&usernum1!=compnum4&&usernum1!=compnum5&&usernum1!=compnum6)||(usernum2!=compnum1&&usernum2!=compnum2&&usernum2!=compnum3&&usernum2!=compnum4&&usernum2!=compnum5&&usernum2!=compnum6)||(usernum3!=compnum1&&usernum3!=compnum2&&usernum3!=compnum3&&usernum3!=compnum4&&usernum3!=compnum5&&usernum3!=compnum6)||(usernum4!=compnum1&&usernum4!=compnum2&&usernum4!=compnum3&&usernum4!=compnum4&&usernum4!=compnum5&&usernum4!=compnum6)||(usernum5!=compnum1&&usernum5!=compnum2&&usernum5!=compnum3&&usernum5!=compnum4&&usernum5!=compnum5&&usernum5!=compnum6)||(usernum6!=compnum1&&usernum6!=compnum2&&usernum6!=compnum3&&usernum6!=compnum4&&usernum6!=compnum5&&usernum6!=compnum6)&&(usernum1!=bonus&&usernum2!=bonus||usernum3!=bonus||usernum4!=bonus||usernum5!=bonus||usernum6!=bonus));
		System.out.println("JACKPOT!");
		System.out.println("You got 2/6 "+counter1+" times");
		System.out.println("You got 2/6 and the bonus "+counter2+" times");
		System.out.println("You got 3/6 "+counter3+" times");	
		System.out.println("You got 4/6 "+counter4+" times");
		System.out.println("You got 5/6 "+counter6+" times");
		System.out.println("You got 5/6 "+counter5+" times");
		time=(counter1+counter2+counter3+counter4+counter5+counter6+losscounter)/52/2;
		System.out.println("It took you "+time+" years to win the jackpot and you lost "+losscounter+" times!");

	}




}
